CREATE DATABASE  IF NOT EXISTS `recipes_tracker`;
USE `recipes_tracker`;

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
`id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `phonenumber` VARCHAR(20) DEFAULT NULL,
  `city` VARCHAR(255) DEFAULT NULL,
  `email` VARCHAR(255) UNIQUE NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;